CREATE TABLE livros (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(80) NOT NULL,
	autor VARCHAR(80) NOT NULL,
	isbn VARCHAR(13) UNIQUE NOT NULL,
	data_publicacao DATE NOT NULL,
	categoria VARCHAR(80) NOT NULL
)